### ISSUE TITLE
Complete UML Model for STIX

### ISSUE THREAD

**Issue by rpiazza** [STIXProject/specifications#20]
1.  Finalize design of how to model Mutually Exclusive XSD Choice in UML
   (indicator:CompositeIndicatorExpression)
2.  Need better name for "RestrictedString" - the UML data type we
   introduced for properties that used to be XSD attributes of type xs:string
   (maybe NoEmbeddedQuotesString)
3.  AssetTypeType needs to inherit from ControlledVocab, but if the type is
   AffectedAssetType.Type is AssetTypeType, then you can't have an uncontrolled
   vocab in that property.
4.  NonPublicDataCompromisedType - same as 3.
5.  Some <<globals>> left in extensions
6.  id/idref can't both be specified.
7.  In incident/ExternalImpactAssessment ModelType it is invalid to have
   neither model_name or model_reference

**Comment by rpiazza** [comment]
Completed for 1.1.1 and 1.2

**Comment by packet-rat** [comment]
Rich and Team: Great job, thanks.

Patrick Maroney
Cell: (609)841-5104

On Aug 21, 2015, at 9:29 AM, Rich Piazza notifications@github.com wrote:

Completed for 1.1.1 and 1.2
